title: Revolting rhymes
subtitle: Make a disgusting poem with Python
description: Create a silly, revolting poem while learning about variables and string methods
version: 1
level: Beginner
language: en
hero_image: images/banner.png
listed: false
copyedit: false
last_tested: "2025-04-04"
landing: true
steps:
  - title: The keys
  - title: Print a specific rhyming sound
    completion:
      - engaged
  - title: Random rhyme key
  - title: Random rhyming words
  - title: Build your first line
  - title: Two lines that rhyme
    completion:
      - internal
  - title: Keep it unique
    completion:
      - external
  - title: "Challenge: Add some things"
    challenge: true
