title: Revolting rhymes
subtitle: Make a disgusting poem with Python
description: Create a silly, revolting poem while learning about variables and string methods
version: 1
level: Beginner
language: en
hero_image: images/banner.png
listed: false
landing: true
copyedit: false
last_tested: "2025-04-04"
steps:
  - title: step_1
  - title: step_2
    completion:
      - engaged
  - title: step_3
  - title: step_4
  - title: step_5
  - title: step_6
  - title: step_7
  - title: step_8
    completion:
      - internal
      - external
